config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
get "about" => "pages#about" 
get "mypage" => "pages#mypage"# creates about_path

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def mypage
end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pinteresting", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    
          </ul>
        </li>
      </ul>
    
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "My Page", mypage_path %></li>
    
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Being a Renegade</h1>
<p> I have no idea what I'm doing but it's amazing!</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to my very first app</h1>
	<p>
	<%= link_to "Log In", "#", class: "btn btn-default btn-lg" %>
	<%= link_to "Sign Up", "#", class: "btn btn-primary btn-lg" %></p>
</div>

app/views/pages/mypage.html.erb
<div class="jumbotron">
	<h1>My Page</h1>
	<span class="label label-danger">Holy F*ck!</span>
	<p>This website is meant to whip me into shape so I can create an awesome site for my own project, 'Renegade' that is all about challenging status quo in the music industry</p>
		<h2>Track my progress</h2>
			<p> As I am teaching myself to code for this I invite you to track how far I've gotten in my One Month process, rock 'n roll! </p>
				<div class="progress">
  					<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="39" aria-valuemin="0" aria-valuemax="100" style="width: 39%">
    				<span class="sr-only">37% Complete (danger)</span>
  				</div>
			</div>
		</div>
</div>